#!/usr/bin/env bash
# SYNOPSIS  peep is a super simple note management tool for the Bash command line
# AUTHOR    Christopher Engelmann
# URL       https://github.com/webcitizen-de/peep

#instdir=$(dirname $BASH_SOURCE)
instdir=~/Documents/dev/__My-Shell-Tools/peep-project
script_name=$(basename $BASH_SOURCE)
script_path="$instdir/$script_name"
config_file="$instdir/peep.config"


if [[ -f $config_file ]]; then
    source "$config_file"
else
    echo "Error. Missing configuration file '$config_file'"
    exit 1
fi

[[ ! -f $path_notes/.trash ]] && mkdir -p "$path_notes/.trash"


function create_file() {

    echo "The note '${1}' doesn't exist yet!"
    echo "Do you like to create it now? [y|n] "
    read answer
    if [[ $answer == "y" ]]; then
        echo
        eval "$editor" "$editor_opt" "$path_notes/$1"
    fi
}

function print_help() {

    echo "Syntax: peep [ [a|alias] [e|edit] [d|delete] [r|rename] ] NOTENAME"
    echo "        peep notes | [empty] trash | config"
    echo
    echo "Create a new note just type:  peep YOUR_NOTENAME"
    echo "Edit a existing file:         peep e YOUR_NOTENAME  OR  peep edit YOUR_NOTENAME"
    echo "List all available notes:     peep notes"
    echo
    echo "Move a note to the trash:     peep d YOUR_NOTENAME  OR  peep delete YOUR_NOTENAME"
    echo "Show the notes in trash:      peep trash"
    echo "Empty the trash:              peep empty trash"
    echo
    echo "Edit the configuration:       peep config"
    echo
}

function check_for_empty_file() {

    counted_words=$(wc -c "$1" | awk '{print $1}')
    if [[ ! counted_words -gt 1 ]]; then
        return 0
    else
        return 1
    fi
}


# concatenate all parameters which makes the evaluation within the case statement easier
parameters="$1 $2"

case "$parameters" in

    "a "*|"alias "*)
        # TODO
    ;;

    "config ")
        eval "$editor" "$config_file"
    ;;

    "d "*|"delete "*)
        if [[ -f $path_notes/$2 ]]; then
            mv -f "$path_notes/$2" "$path_notes/.trash"
        else
            echo "Could not delete the note $1 since it does not exist."
        fi
    ;;

    "empty trash")
        echo "ATTENTION: I going to delete all of these files for good:"
        echo
        command ls -FG "$path_notes/.trash"
        echo
        echo "Please confirm that operation (yes)"
        read -p "--> " confirmation

        if [[ $confirmation == "yes" ]]; then
            eval rm -f "$path_notes/.trash/*"
        else
            echo "Execution aborted"
        fi
    ;;

    "e "*|"edit "*)
        if [[ -f $path_notes/$2 ]]; then
            eval "$editor" "$editor_opt" "$path_notes/$2"

        elif [[ $2 != "" ]]; then
            create_file "$2"

        elif [[ $2 == "" ]]; then
            eval "$editor" "$editor_opt" "$path_notes/default"
        fi
    ;;

    "n "*|"notes "*)
        echo "$path_notes"
        if [[ $2 != "" ]]; then
            command ls -FG "$path_notes" | command egrep "$2"
        else
            command ls -FG "$path_notes"
        fi
    ;;

    "r "*|"rename "*)

        if [[ -f $path_notes/$2 && ! -z $3 ]]; then
            command mv "$path_notes/$2" "$path_notes/$3"
        else
            if [[ ! -f $path_notes/$2 ]]; then
                echo "A note with the name '$2' does not exist."
            else
                echo "Please check your arguments and if !"
                echo "Syntax: peep rename NOTENAME NEW_NOTENAME"
                echo "        peep r      NOTENAME NEW_NOTENAME"
            fi
        fi
    ;;

    " ")
        print_help
    ;;

    "trash ")
        echo "$path_notes/.trash"
        command ls -FG "$path_notes/.trash"
    ;;

    *)
        if [[ -f $path_notes/$1 ]]; then

            if ! command egrep '\w' $path_notes/$1 &> /dev/null; then
                echo "$path_notes/$1"
                echo "The note '$1' is empty."
            else
                eval "$printing_tool" "$path_notes/$1"
            fi

        elif [[ $2 == "" ]]; then
            create_file "$1"

        else
            print_help
        fi
    ;;
esac
